//
//  RecipesPresenter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecipesPresentationLogic {
    func presentRecipes(response: RecipesList.DisplayRecipes.Response)
    func presentError(response: RecipesList.HandleError.Response)
}

class RecipesPresenter: RecipesPresentationLogic {

    // MARK: - Public properties
    
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Presenting Logic

    func presentRecipes(response: RecipesList.DisplayRecipes.Response) {
        let cells = response.recipes.map { RecipeCellViewModel(recipe: $0) }

        let viewModel = RecipesList.DisplayRecipes.ViewModel(cells: cells)
        viewController?.displayRecipes(viewModel: viewModel)
    }

    func presentError(response: RecipesList.HandleError.Response) {
        let errorMessage = response.error.localizedDescription
        let viewModel = RecipesList.HandleError.ViewModel(errorMessage: errorMessage)
        viewController?.displayError(viewModel: viewModel)
    }
}
