//
//  RecipesViewController.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SnapKit
import UIKit

protocol HomeDisplayLogic: AnyObject {
    func displayRecipes(viewModel: RecipesList.DisplayRecipes.ViewModel)
    func displayError(viewModel: RecipesList.HandleError.ViewModel)
}

class RecipesViewController: UIViewController, HomeDisplayLogic {

    var interactor: RecipesBuisnessLogic?
    var router: (RecipesRoutingLogic & RecipesDataPassing)?

    // MARK: - Private properties

    private var isLoadingNext = false

    private var viewModel: RecipesList.DisplayRecipes.ViewModel? {
        didSet {
            recipeCollectionView.reloadData()
        }
    }

    // MARK: - Views

    private let loadingIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView(style: .large)
        indicator.color = .mainTintColor
        indicator.hidesWhenStopped = true
        return indicator
    }()

    let recipeCollectionView = RecipeCollectionView()

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        RecipesConfigurator.shared.configure(with: self)
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        RecipesConfigurator.shared.configure(with: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        recipeCollectionView.delegate = self
        recipeCollectionView.dataSource = self
        setupNavigationBar()
        setupTabBar()
        setupConstraints()
        start()
    }

    // MARK: - Private methods

    private func setupNavigationBar() {

        let searchButton = UIBarButtonItem(image: UIImage(systemName: "magnifyingglass"),
                                           style: .plain,
                                           target: self,
                                           action: #selector(showFilters))
        navigationItem.backBarButtonItem?.setTitleTextAttributes([.font: UIFont.handlee()], for: .normal)
        searchButton.tintColor = .mainTintColor
        navigationItem.rightBarButtonItem = searchButton
    }

    private func setupTabBar() {
        tabBarController?.tabBar.isTranslucent = false
        tabBarController?.tabBar.barTintColor = .mainAccentColor
        tabBarController?.tabBar.tintColor = .mainTintColor
        tabBarController?.tabBar.backgroundColor = .mainAccentColor
        tabBarController?.tabBar.unselectedItemTintColor = .disabledColor
        tabBarItem = UITabBarItem(title: "List", image: UIImage(systemName: "list.bullet"), tag: 0)
    }

    private func setupConstraints() {
        view.addSubview(recipeCollectionView)
        recipeCollectionView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }

        view.addSubview(loadingIndicator)
        loadingIndicator.snp.makeConstraints { make in
            make.center.equalToSuperview()
        }
    }

    private func start() {
        loadingIndicator.startAnimating()
        interactor?.viewDidLoad()
    }

    private func loadNextRecipes() {
        if !isLoadingNext {
            interactor?.loadNextRecipes()
        }
        isLoadingNext = true
    }

    @objc private func showFilters() {
        FeedbackService.shared.makeFeedback(event: .impactOccured)
        router?.presentFilters()
    }

    // MARK: - Display Logic

    func displayRecipes(viewModel: RecipesList.DisplayRecipes.ViewModel) {
        DispatchQueue.main.async { [unowned self] in
            self.viewModel = viewModel
            loadingIndicator.stopAnimating()
            isLoadingNext = false
        }
    }

    func displayError(viewModel: RecipesList.HandleError.ViewModel) {
        showAlert(title: "Something went wrong", message: viewModel.errorMessage)
        FeedbackService.shared.makeFeedback(event: .notificationError)
    }
}

// MARK: - Extensions

extension RecipesViewController: UICollectionViewDelegateFlowLayout {

    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        router?.routeToRecipeDetails()
        collectionView.deselectItem(at: indexPath, animated: true)
    }

    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if scrollView.contentSize.height - scrollView.frame.height - 300 <= scrollView.contentOffset.y {
            loadNextRecipes()
        }
    }
}

extension RecipesViewController: UICollectionViewDataSource {

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        viewModel?.cells.count ?? 0
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: RecipeCell.reuseID,
                                                          for: indexPath) as? RecipeCell
        else {
            return UICollectionViewCell()
        }
        if let cellVM = viewModel?.cells[indexPath.item] {
            cell.viewModel = cellVM
        }
        return cell
    }
}

extension RecipesViewController: FiltersViewControllerDelegate {
    func reloadRecipies() {
        viewModel = nil
        start()
    }
}
