//
//  HomePresenter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentRandomRecipies(response: Home.LoadRandomRecipies.Response)
    func presentError(response: Home.HandleError.Response)
}

class HomePresenter: HomePresentationLogic {
    
    weak var viewController: HomeDisplayLogic?

    // MARK: Private properties

    private let networkService: NetworkService

    init(networkService: NetworkService) {
        self.networkService = networkService
    }

    func presentRandomRecipies(response: Home.LoadRandomRecipies.Response) {
        let recipies = response.recipeRespone.hits.map { $0.recipe }
        let cells = recipies.map { recipe in
            RecipeCellViewModel(dishName: recipe.label, imageURL: recipe.image)
        }

        let viewModel = Home.LoadRandomRecipies.ViewModel(cells: cells)
        viewController?.displayRandomRecipies(viewModel: viewModel)
    }

    func presentError(response: Home.HandleError.Response) {

    }
}
