//
//  HomeModels.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Use cases

    enum LoadRecipes {

        struct Response {
            let recipes: [Recipe]
        }

        struct ViewModel {
            let cells: [RecipeCellViewModelRepresentable]
        }
    }

    enum LoadNextRecipes {
        struct Response {
            let recipeRespone: RecipeResponse
        }

        struct ViewModel {
            let cells: [RecipeCellViewModelRepresentable]
        }
    }

    enum HandleError {
        struct Response {
            let error: Error
        }

        struct ViewModel {
            let errorMessage: String
        }
    }
}

struct RecipeCellViewModel: RecipeCellViewModelRepresentable {
    let dishName: String
    let imageURL: String
}
