//
//  HomeRouter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToRecipeDetails()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {

    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

    func routeToRecipeDetails() {
        let destination = RecipeDetailsViewController()

        guard
            let source = viewController,
            var destinationDS = destination.router?.dataStore,
            let dataStore
        else {
            return
        }
        passDataToRecipeDetails(source: dataStore, destination: &destinationDS)
        navigateToRecipeDetails(source: source, destination: destination)
    }


// MARK: Passing data to other screen

    func passDataToRecipeDetails(source: HomeDataStore, destination: inout RecipeDetailsDataStore) {
        guard let viewController else { return }
        guard let indexPath = viewController.collectionView.indexPathsForSelectedItems?.first else { return }
        let recipies = source.recipieResponse?.hits.compactMap { $0.recipe }
        guard let recipe = recipies?[indexPath.item] else { return }
        destination.recipe = recipe
    }

    func navigateToRecipeDetails(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
}
