//
//  HomePresenter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentRecipes(response: Home.LoadRecipes.Response)
    func presentError(response: Home.HandleError.Response)
}

class HomePresenter: HomePresentationLogic {

    // MARK: - Public properties
    
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Presenting Logic

    func presentRecipes(response: Home.LoadRecipes.Response) {
        let cells = response.recipes.map { recipe in
            RecipeCellViewModel(dishName: recipe.label, imageURL: recipe.image)
        }

        let viewModel = Home.LoadRecipes.ViewModel(cells: cells)
        viewController?.displayRecipes(viewModel: viewModel)
    }

    func presentError(response: Home.HandleError.Response) {
        let errorMessage = response.error.localizedDescription
        let viewModel = Home.HandleError.ViewModel(errorMessage: errorMessage)
        viewController?.displayError(viewModel: viewModel)
    }
}
