//
//  FavoritesRouter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 28.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoritesRoutingLogic {
    func routeToRecipeDetails()
}

protocol FavoritesDataPassing {
    var dataStore: FavoritesDataStore? { get }
}

class FavoritesRouter: FavoritesRoutingLogic, FavoritesDataPassing {

    weak var viewController: FavoritesViewController?
    var dataStore: FavoritesDataStore?

    func routeToRecipeDetails() {

        let destination = RecipeDetailsViewController()

        guard
            let source = viewController,
            var destinationDS = destination.router?.dataStore,
            let dataStore
        else {
            return
        }
        passDataToRecipeDetails(source: dataStore, destination: &destinationDS)
        navigateToRecipeDetails(source: source, destination: destination)
    }

    private func passDataToRecipeDetails(source: FavoritesDataStore, destination: inout RecipeDetailsDataStore) {
        guard let viewController else { return }
        guard let indexPath = viewController.collectionView.indexPathsForSelectedItems?.first else { return }
        let recipe = source.recipes[indexPath.item]
        destination.recipe = recipe
    }

    private func navigateToRecipeDetails(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
}
