//
//  FavoritesInteractor.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 28.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesBusinessLogic {
    func doSomething(request: Favorites.Something.Request)
//    func doSomethingElse(request: Favorites.SomethingElse.Request)
}

protocol FavoritesDataStore {
    //var name: String { get set }
}

class FavoritesInteractor: FavoritesBusinessLogic, FavoritesDataStore {
    var presenter: FavoritesPresentationLogic?
    //var name: String = ""

    // MARK: Do something (and send response to FavoritesPresenter)

    func doSomething(request: Favorites.Something.Request) {

        let response = Favorites.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Favorites.SomethingElse.Request) {
//        worker = FavoritesWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Favorites.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
