//
//  FavoritesPresenter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 28.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesPresentationLogic {
    func presentSomething(response: FavoritesList.ShowFavorites.Response)
}

class FavoritesPresenter: FavoritesPresentationLogic {
    weak var viewController: FavoritesDisplayLogic?

    // MARK: Parse and calc respnse from FavoritesInteractor and send simple view model to FavoritesViewController to be displayed

    func presentSomething(response: FavoritesList.ShowFavorites.Response) {
        let cells = response.recipes.map { RecipeCellViewModel(recipe: $0) }
        let viewModel = FavoritesList.ShowFavorites.ViewModel(cells: cells)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
