//
//  RecipeDetailsInteractor.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecipeDetailsBusinessLogic {
    func start()
}

protocol RecipeDetailsDataStore {
    var recipe: Recipe? { get set }
}

class RecipeDetailsInteractor: RecipeDetailsBusinessLogic, RecipeDetailsDataStore {

    var recipe: Recipe?

    var presenter: RecipeDetailsPresentationLogic?
    var worker: RecipeDetailsWorker?

    // MARK: Do something (and send response to RecipeDetailsPresenter)

    func start() {
        guard let recipe else { return }
        let response = RecipeDetails.ShowRecipeDetails.Response(recipe: recipe)
        presenter?.presentRecipeDetails(response: response)
    }
}
