//
//  RecipeDetailsPresenter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecipeDetailsPresentationLogic {
    func presentRecipeDetails(response: RecipeDetails.ShowRecipeDetails.Response)
}

class RecipeDetailsPresenter: RecipeDetailsPresentationLogic {
    weak var viewController: RecipeDetailsDisplayLogic?

    // MARK: Parse and calc respnse from RecipeDetailsInteractor and send simple view model to RecipeDetailsViewController to be displayed

    func presentRecipeDetails(response: RecipeDetails.ShowRecipeDetails.Response) {
        let recipe = response.recipe
        var totalTime: String {
            if let time = recipe.totalTime, time != 0 {
                let formattedTime = String(format: "%.f", time)
                return "Time: \(formattedTime) min"
            } else {
                return ""
            }
        }

        #warning("remove force unwrapping")

        guard let totalNutrients = recipe.totalNutrients?.allProperties()
            .map({ $0.value as! Nutrient })
            .filter({ $0.quantity != 0 })
            .filter({$0.unit == "g"})
        else { return }

        guard let dailyValues = recipe.totalDaily?.allProperties()
            .map({ $0.value as! Nutrient })
            .filter( { $0.quantity != 0 })
        else { return }

        guard let vitamins = recipe.totalNutrients?.allProperties()
            .map({$0.value as! Nutrient})
            .filter({$0.unit != "g" })
            .filter({ $0.quantity != 0 })
        else { return }

        let nutrientViewModels = totalNutrients.map { nutrient in
            let dailyPercentage = (dailyValues.first(where: { $0.label == nutrient.label })?.quantity ?? 0) / (recipe.yield ?? 1)
            return NutrientRowViewModel(name: nutrient.label ?? "",
                                        value: String(format: "%.f", (nutrient.quantity ?? 0) / (recipe.yield ?? 1)),
                                        unit: nutrient.unit ?? "g",
                                        dailyPercentage: String(format: "%.f", dailyPercentage))
        }

        let vitaminViewModels = vitamins.map { vitamin in
            let dailyPercentage = (dailyValues.first(where: { $0.label == vitamin.label })?.quantity ?? 0) / (recipe.yield ?? 1)
            return NutrientRowViewModel(name: vitamin.label ?? "",
                                        value: String(format: "%.f", vitamin.quantity ?? 0),
                                 unit: vitamin.unit ?? "mg",
                                 dailyPercentage: String(format: "%.f", dailyPercentage))
        }

        let nutritionFactsViewModel = NutritionFactsViewModel(servings: String(format: "%.f", recipe.yield ?? 1),
                                                              caloriesPerServing: String(format: "%.f", (recipe.calories ?? 0) / (recipe.yield ?? 1)),
                                                              nutrients: nutrientViewModels,
                                                              vitamins: vitaminViewModels)

        let viewModel = RecipeDetails.ShowRecipeDetails.ViewModel(imageURL: recipe.image ,
                                                                  recipeURL: recipe.url ?? "",
                                                                  source: recipe.source ?? "",
                                                                  title: recipe.label,
                                                                  dietLabels: recipe.dietLabels ?? [],
                                                                  healthLabels: recipe.healthLabels ?? [],
                                                                  cautions: recipe.cautions ?? [],
                                                                  ingridientLines: recipe.ingredientLines ?? [],
                                                                  calories: String(format: "%.f", recipe.calories ?? 0),
                                                                  totalWeight: String(format: "%.f", recipe.totalWeight ?? 0),
                                                                  coockingTime: totalTime,
                                                                  cuisineTypes: recipe.cuisineType ?? [],
                                                                  dishTypes: recipe.dishType ?? [],
                                                                  mealTypes: recipe.mealType ?? [],
                                                                  nutritionFactsViewModel: nutritionFactsViewModel)
        viewController?.displayRecipeDetails(viewModel: viewModel)
    }
}
