//
//  RecipeDetailsModels.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RecipeDetails {
    // MARK: Use cases

    enum ShowRecipeDetails {

        struct Response {
            let recipe: Recipe
        }

        struct ViewModel {
            let imageURL: String
            let recipeURL: String
            let source: String
            let title: String
            let dietLabels: [String]
            let healthLabels: [String]
            let cautions: [String]
            let ingridientLines: [String]
            let calories: String
            let totalWeight: String
            let coockingTime: String
            let cuisineTypes: [String]
            let dishTypes: [String]
            let mealTypes: [String]
            let nutritionFactsViewModel: NutritionFactsViewRepresentable
        }
    }
}

struct NutritionFactsViewModel: NutritionFactsViewRepresentable {
    var servings: String
    var caloriesPerServing: String
    var nutrients: [NutrientRowViewRepresentable]
    var vitamins: [NutrientRowViewRepresentable]
}

struct NutrientRowViewModel: NutrientRowViewRepresentable {
    var name: String
    var value: String
    var unit: String
    var dailyPercentage: String
}
