//
//  RecipeDetailsPresenter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecipeDetailsPresentationLogic {
    func presentRecipeDetails(response: RecipeDetails.ShowRecipeDetails.Response)
}

class RecipeDetailsPresenter: RecipeDetailsPresentationLogic {
    weak var viewController: RecipeDetailsDisplayLogic?

    // MARK: Parse and calc respnse from RecipeDetailsInteractor and send simple view model to RecipeDetailsViewController to be displayed

    func presentRecipeDetails(response: RecipeDetails.ShowRecipeDetails.Response) {
        let recipe = response.recipe
        var totalTime: String {
            if let time = recipe.totalTime, time != 0 {
                let formattedTime = String(format: "%.f", time)
                return "Time: \(formattedTime) min"
            } else {
                return ""
            }
        }
        let viewModel = RecipeDetails.ShowRecipeDetails.ViewModel(imageURL: recipe.image ,
                                                                  recipeURL: recipe.url ?? "",
                                                                  source: recipe.source ?? "",
                                                                  title: recipe.label,
                                                                  dietLabels: recipe.dietLabels ?? [],
                                                                  healthLabels: recipe.healthLabels ?? [],
                                                                  cautions: recipe.cautions ?? [],
                                                                  ingridientLines: recipe.ingredientLines ?? [],
                                                                  calories: String(format: "%.f", recipe.calories ?? 0),
                                                                  totalWeight: String(format: "%.f", recipe.totalWeight ?? 0),
                                                                  coockingTime: totalTime,
                                                                  cuisineTypes: recipe.cuisineType ?? [],
                                                                  dishTypes: recipe.dishType ?? [],
                                                                  mealTypes: recipe.mealType ?? [])
        viewController?.displayRecipeDetails(viewModel: viewModel)
    }
}
