//
//  RecipeDetailsPresenter.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecipeDetailsPresentationLogic {
    func presentSomething(response: RecipeDetails.Something.Response)
}

class RecipeDetailsPresenter: RecipeDetailsPresentationLogic {
    weak var viewController: RecipeDetailsDisplayLogic?

    // MARK: Parse and calc respnse from RecipeDetailsInteractor and send simple view model to RecipeDetailsViewController to be displayed

    func presentSomething(response: RecipeDetails.Something.Response) {
        let viewModel = RecipeDetails.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: RecipeDetails.SomethingElse.Response) {
//        let viewModel = RecipeDetails.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
