//
//  RecipeDetailsInteractor.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecipeDetailsBusinessLogic {
    func doSomething(request: RecipeDetails.Something.Request)
//    func doSomethingElse(request: RecipeDetails.SomethingElse.Request)
}

protocol RecipeDetailsDataStore {
    var recipe: Recipe? { get set }
}

class RecipeDetailsInteractor: RecipeDetailsBusinessLogic, RecipeDetailsDataStore {

    var recipe: Recipe?

    var presenter: RecipeDetailsPresentationLogic?
    var worker: RecipeDetailsWorker?
    //var name: String = ""

    // MARK: Do something (and send response to RecipeDetailsPresenter)

    func doSomething(request: RecipeDetails.Something.Request) {
        worker = RecipeDetailsWorker()
        worker?.doSomeWork()

        let response = RecipeDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
