//
//  RecipeDetailsModels.swift
//  MakeSomeFood
//
//  Created by Aleksandr Kretov on 14.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RecipeDetails {
    enum ShowRecipeDetails {
        struct Response {
            let recipe: Recipe
            let existingIngredients: [Ingredient]
        }
        struct ViewModel {
            let imageURL: String
            let recipeURL: String
            let title: String
            let totalWeight: String
            let coockingTime: String?
            let nutritionFactsViewModel: NutritionFactsViewRepresentable
            let ingredientRowiewModels: [IngredientViewModelProtocol]
            var isFavorite: Bool
        }
    }

    enum HandleIngredient {
        struct Request {
            let name: String
            let state: Bool
        }
    }

    enum HandleFavorites {
        struct Response {
            let state: Bool
        }
        struct ViewModel {
            let state: Bool
        }
    }
}

struct NutritionFactsViewModel: NutritionFactsViewRepresentable {
    var servings: String
    var caloriesPerServing: String
    var nutrients: [NutrientRowViewRepresentable]
    var vitamins: [NutrientRowViewRepresentable]
}

struct NutrientRowViewModel: NutrientRowViewRepresentable {
    var name: String
    var value: String
    var unit: String
    var dailyPercentage: String
}

struct IngredientRowViewModel: IngredientViewModelProtocol {
    var imageURL: String
    var name: String
    var weight: String
    var isExisting: Bool
}
